name: cc-k6
services:
  backend:
    build: .
    environment:
      ADMIN_AUTOSEED: "true"
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin123
      FRONT_DIST_DIR: /app/public
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD-SHELL","python - <<'PY'\nimport sys,urllib.request\ntry:\n  with urllib.request.urlopen('http://localhost:8001/healthz', timeout=2) as r:\n    sys.exit(0 if r.status==200 else 1)\nexcept Exception:\n  sys.exit(1)\nPY"]
      interval: 5s
      timeout: 3s
      retries: 30

# k6 se lance a la demande via scripts/CI; pas de container resident ici.
