[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E","F","I"]
ignore = ["E203","E266","E501"]
exclude = [
"docs","site",".venv","build","dist","scripts/bash","scripts/ps1",
"node_modules","backups","logs"
]

[tool.ruff.lint.isort]
known-first-party = ["backend"]

[tool.ruff.lint.per-file-ignores]
"backend/tests/*" = ["F401","F841","E402"]
"**/__init__.py" = ["F401"]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
warn_unused_ignores = true
no_implicit_optional = true
strict_optional = true
check_untyped_defs = false
disallow_untyped_defs = false
exclude = "(^|/)(docs|site|.venv|build|dist|scripts)/"

[tool.mypy-backend]
module = "backend.*"
