global:
  resolve_timeout: 5m
route:
  receiver: "null"
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 2h
receivers:
  - name: "null"
    webhook_configs: []

# Integration e-mail/telegram a ajouter en prod via variables d'environnement.
