global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "ccapi"
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:8001"]
        labels:
          service: "ccapi-backend"
