name: CLI in Docker
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "backend/**"
      - "Dockerfile"
      - "scripts/bash/docker_ccadmin.sh"
      - "PS1/docker_ccadmin.ps1"
      - ".github/workflows/cli_docker.yml"
  push:
    branches: [ main ]

jobs:
  cli-docker:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build image
        run: docker build --pull -t ccapi:cli-ci .
      - name: Sanity - ccadmin present
        run: |
          set -eux
          docker run --rm ccapi:cli-ci sh -lc 'echo PATH=$PATH; which ccadmin || true; ccadmin --help || (python -m app.cli --help && exit 0)'
          docker run --rm ccapi:cli-ci sh -lc 'ccadmin --version || python -m app.cli --version || true'
      - name: Prepare shared volume
        run: docker volume create ccapi_cli_ci
      - name: CLI list (should succeed)
        run: docker run --rm -e DB_DSN="sqlite:////data/cc.db" -v ccapi_cli_ci:/data ccapi:cli-ci ccadmin list
      - name: CLI create user (first should succeed)
        run: docker run --rm -e DB_DSN="sqlite:////data/cc.db" -v ccapi_cli_ci:/data ccapi:cli-ci ccadmin create --username ciuser --password pw
      - name: CLI create duplicate (should fail exit code 1)
        run: |
          set +e
          docker run --rm -e DB_DSN="sqlite:////data/cc.db" -v ccapi_cli_ci:/data ccapi:cli-ci ccadmin create --username ciuser --password pw
          rc=$?
          echo "duplicate rc=$rc"
          test "$rc" -eq 1
      - name: CLI promote user (should succeed)
        run: docker run --rm -e DB_DSN="sqlite:////data/cc.db" -v ccapi_cli_ci:/data ccapi:cli-ci ccadmin promote --username ciuser
      - name: Debug info on failure
        if: failure()
        run: |
          set +e
          echo "=== docker images ==="; docker images
          echo "=== try python -m app.cli --help in image ==="
          docker run --rm ccapi:cli-ci python -m app.cli --help || true
          echo "=== try list with high verbosity ==="
          docker run --rm -e DB_DSN="sqlite:////data/cc.db" -v ccapi_cli_ci:/data ccapi:cli-ci sh -lc 'ccadmin list || python -m app.cli list || true'
