name: deps-audit
on:
  pull_request:
    paths:
      - "requirements*.txt"
      - ".github/workflows/deps-audit.yml"
  push:
    branches: [ main ]
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install pip-audit
        run: pip install pip-audit==2.7.3
      - name: Audit runtime deps (requirements.txt)
        id: audit
        continue-on-error: true
        run: |
          if [ -f requirements.txt ]; then \
            pip-audit -r requirements.txt -l --progress-spinner=off --strict=false --format sarif -o pip-audit.sarif || true; \
          else \
            echo "no requirements.txt"; \
          fi
      - name: Upload SARIF (GitHub code scanning)
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pip-audit.sarif
