name: k6-smoke
on:
  pull_request:
    paths:
      - "scripts/k6/**"
      - ".github/workflows/k6-smoke.yml"
      - "backend/**"
jobs:
  k6-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps (uvicorn + fastapi + prometheus fallback)
        run: |
          python -m pip install -U pip
          pip install uvicorn fastapi prometheus-client
      - name: Start API (prefer backend, fallback to mock)
        shell: bash
        run: |
          set -e
          export PYTHONPATH=backend:.
          # demarrage preferentiel de l'app si dispo
          python -c "import importlib; import sys; sys.exit(0 if importlib.util.find_spec('backend.app.main') else 1)" \
          && nohup python -m uvicorn backend.app.main:app --host 127.0.0.1 --port 8000 >/dev/null 2>&1 \
          || nohup python -m uvicorn scripts.k6.mock_api:app --host 127.0.0.1 --port 8000 >/dev/null 2>&1 &
          for i in {1..10}; do code=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8000/healthz || true); [ "$code" = "200" ] && break; sleep 1; done
          [ "$code" = "200" ] || (echo "healthz KO"; exit 2)
      - name: Run k6 smoke
        uses: grafana/k6-action@v0.3.1
        with:
          filename: scripts/k6/smoke.js
        env:
          BASE_URL: http://127.0.0.1:8000
