name: k6-smoke
on:
  pull_request:
    paths:
      - "backend/**"
      - "scripts/k6/**"
      - ".github/workflows/k6-smoke.yml"
jobs:
  k6-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps (backend or mock)
        run: |
          python -m pip install -U pip
          pip install fastapi uvicorn prometheus-client
      - name: Start API (prefer backend, fallback mock) + wait
        shell: bash
        run: |
          set -euo pipefail
          export PYTHONPATH=backend:.
          # backend prioritaire
          if python - <<'PY'
import importlib.util,sys
sys.exit(0 if importlib.util.find_spec('backend.app.main') else 1)
PY
          then
            nohup python -m uvicorn backend.app.main:app --host 127.0.0.1 --port 8000 >/tmp/api.log 2>&1 &
          else
            nohup python -m uvicorn scripts.k6.mock_api:app --host 127.0.0.1 --port 8000 >/tmp/api.log 2>&1 &
          fi
          for i in $(seq 1 30); do
            code=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8000/healthz || true)
            [ "$code" = "200" ] && break
            sleep 1
          done
          echo "healthz HTTP=$code"
          [ "$code" = "200" ] || (echo "healthz KO"; tail -n 200 /tmp/api.log || true; exit 2)
      - name: Run k6 smoke
        uses: grafana/k6-action@v0.3.1
        with:
          filename: scripts/k6/smoke.js
        env:
          BASE_URL: http://127.0.0.1:8000
      - name: Tail API logs (debug on failure)
        if: failure()
        run: tail -n +200 /tmp/api.log || true
