name: lint-python
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install linters (versions pinnees)
        run: |
          python -m pip install -U pip
          pip install ruff==0.6.4 mypy==1.10.0
      - name: Ruff (backend)
        run: ruff check backend
      - name: MyPy (app+cli)
        run: mypy backend/app backend/cli
