name: obs-smoke
on:
  pull_request:
    paths: [ "backend/**", "requirements*.txt", ".github/workflows/obs-smoke.yml" ]
jobs:
  obs:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps backend (requirements si present)
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install fastapi uvicorn sqlalchemy prometheus-client prometheus-fastapi-instrumentator; fi
      - name: Start API + METRICS + wait
        shell: bash
        run: |
          set -euo pipefail
          export METRICS_ENABLED=1; export METRICS_PATH=/metrics; export PYTHONPATH=backend
          nohup python -m uvicorn backend.app.main:app --host 127.0.0.1 --port 8001 >/tmp/api_obs.log 2>&1 &
          for i in $(seq 1 30); do code=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8001/metrics || true); [ "$code" = "200" ] && break; sleep 1; done
          echo "metrics HTTP=$code"; [ "$code" = "200" ] || (tail -n 200 /tmp/api_obs.log || true; exit 2)
      - name: Status-only
        run: test "$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8001/metrics)" = "200"
      - name: API logs (on failure)
        if: failure()
        run: tail -n +1 /tmp/api_obs.log || true
