name: release
on:
  push:
    tags:
      - 'v*.*.*'
permissions:
  contents: write
jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read version
        id: v
        run: |
          echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release v${{ steps.v.outputs.version }}
          tag_name: v${{ steps.v.outputs.version }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
