name: Release
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version SemVer (X.Y.Z). Cree un tag si defini."
        required: false
        type: string
permissions:
  contents: read
  packages: write
  id-token: write
jobs:
  prepare-tag:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.version != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create tag
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag "v${{ inputs.version }}" -a -m "release v${{ inputs.version }}"
          git push origin "v${{ inputs.version }}"
  build-and-publish:
    runs-on: ubuntu-latest
    needs: [prepare-tag]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11", cache: "pip" }
      - uses: actions/setup-node@v4
        with: { node-version: "20", cache: "npm", cache-dependency-path: "web/package-lock.json" }
      - name: Lints + tests
        run: |
          python -m pip install --upgrade pip
          pip install -e backend[dev]
          python -m ruff check backend
          python -m mypy backend
          pytest -q --cov=backend
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          provenance: false
          tags: ghcr.io/${{ github.repository_owner }}/ccapi:${{ github.ref_name }}
          platforms: linux/amd64
      - name: Summary
        run: |
          echo "Pushed ghcr.io/${{ github.repository_owner }}/ccapi:${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
