name: scan-secrets
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Gitleaks (workspace only, PR)
        if: ${{ github.event_name == 'pull_request' }}
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --no-banner --redact --no-git --report-format sarif --report-path gitleaks.sarif --exit-code 1 --config gitleaks.toml
      - name: Run Gitleaks (push on main, with baseline)
        if: ${{ github.event_name == 'push' }}
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --no-banner --redact --report-format sarif --report-path gitleaks.sarif --exit-code 1 --config gitleaks.toml --baseline-path .gitleaks.baseline.json
